// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzhdkvwppffolykdthfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aGRrdndwcGZmb2x5a2R0aGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzI1MTIsImV4cCI6MjA2OTEwODUxMn0.AenS8Fr2a_8jkoCTXoY_akftpXhxJpe0Ad8h3cs4u_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});